name: eShields
main: io.github.lukeeff.eShields
version: 1.2.3
api-version: 1.15
commands: 
   eshields:
      description: To be determined.
      usage: /eshields
   ecategory:
      description: Retrieve possible category.
      usage: /ecategory <category>.